### ISSUE TITLE
Cant compile source code on latest SDK and NDK.

### ISSUE THREAD

**Issue by Dhananjay-Khairnar** [CubePilot/qgroundcontrol-herelink#18]
- Target Compilation : Herelink.
- Host OS : Windows 10
- Platform : QT 5.14
- Android NDK : 21.3.6
- Android SDK : 26.1.1

**Compilation Logs**
`12:12:31: The process "C:\Qt\Qt5.14.1\5.14.1\android\bin\qmake.exe" exited normally.
12:12:31: Starting: "C:\Users\Owner\AppData\Local\Android\Sdk\ndk\21.3.6528147\prebuilt\windows-x86_64\bin\make.exe" -f C:/Dhananjay/build-qgroundcontrol-Android_for_armeabi_v7a_arm64_v8a_x86_x86_64_Clang_Qt_5_14_1_for_Android_540d4d-Debug/Makefile qmake_all
make: Nothing to be done for 'qmake_all'.
12:12:32: The process "C:\Users\Owner\AppData\Local\Android\Sdk\ndk\21.3.6528147\prebuilt\windows-x86_64\bin\make.exe" exited normally.
12:12:32: Starting: "C:\Users\Owner\AppData\Local\Android\Sdk\ndk\21.3.6528147\prebuilt\windows-x86_64\bin\make.exe" -j4
linking debug\libQGroundControl_armeabi-v7a.so 
clang++: error: no such file or directory: '@obj\object_script.debug\libQGroundControl_armeabi-v7a.so.Armeabi-v7a'
make: *** [Makefile:1403: debug\libQGroundControl_armeabi-v7a.so] Error 1`

**Comment by kasparjj** [comment]
Hi @Dhananjay-Khairnar 

Did you manage to compile the project? 
I have similar problems with compiling.

Best regards

**Comment by Dhananjay-Khairnar** [comment]
I have compiled the code. but its not look the same like QGCS comes pre installed in Herelink. Video streaming is not enabled dont know where to configure it. 

Host OS : Ubuntu 21.04
Android build SDK - 29
Android NDK - 15.2.4203891([android-ndk-r15c-linux-x86_64.zip](https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip))  (also requires 21.3.6528147 for make)
QT = 5.11.0

Changes required in files:

1. qgroundcontrol/android/AndroidManifest.xml

- `<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29"/>`
2. qgroundcontrol/src/VideoStreaming/VideoStreaming.pri

- L 78 `GST_ROOT = $$PWD/../../gstreamer-1.0-android-armv7-1.5.2` (set both GST_ROOT path to same)
- L 110 `-lgstvideo-1.0 -lavformat -lavcodec -lavutil -lx264 \#-lavfilter -lswresample \`
- L 114 add belove `LIBS += -L$$PWD/../../lib -lavresample`

**Comment by HimanshuChowdharyIndia** [comment]
> I have compiled the code. but its not look the same like QGCS comes pre installed in Herelink. Video streaming is not enabled dont know where to configure it.
> 
> Host OS : Ubuntu 21.04 Android build SDK - 29 Android NDK - 15.2.4203891([android-ndk-r15c-linux-x86_64.zip](https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip)) (also requires 21.3.6528147 for make) QT = 5.11.0
> 
> Changes required in files:
> 
> 1. qgroundcontrol/android/AndroidManifest.xml
> 
> * `<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29"/>`
> 
> 2. qgroundcontrol/src/VideoStreaming/VideoStreaming.pri
> 
> * L 78 `GST_ROOT = $$PWD/../../gstreamer-1.0-android-armv7-1.5.2` (set both GST_ROOT path to same)
> * L 110 `-lgstvideo-1.0 -lavformat -lavcodec -lavutil -lx264 \#-lavfilter -lswresample \`
> * L 114 add belove `LIBS += -L$$PWD/../../lib -lavresample`

Hi @Dhananjay-Khairnar ,

I tried on QT 5.11.0 and QT 5.15.2. 
I am using NDK 21.3.6528147. I also tried using NDK android-ndk-r15c.

Actually code gets compiled but I get error while linking .so file. 

herelink did not provided any system environment guidance.

I am trying to build <herelink-v4.0.8> - https://github.com/CubePilot/qgroundcontrol-herelink

Please find below exception I got:

obj/QGeoCodeReplyQGC.o(.ARM.extab+0x0): error: undefined reference to '__gxx_personality_v0'
obj/QGeoCodeReplyQGC.o(.ARM.extab+0xe4): error: undefined reference to '__gxx_personality_v0'
obj/QGeoCodeReplyQGC.o(.ARM.extab+0xfc): error: undefined reference to '__gxx_personality_v0'
obj/QGeoCodeReplyQGC.o(.ARM.extab+0x114): error: undefined reference to '__gxx_personality_v0'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject.h:266: error: undefined reference to 'operator new(unsigned int)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject.h:266: error: undefined reference to 'operator delete(void*)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobjectdefs_impl.h:415: error: undefined reference to 'operator delete(void*)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:626: error: undefined reference to '__cxa_begin_catch'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:628: error: undefined reference to '__cxa_rethrow'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:629: error: undefined reference to '__cxa_end_catch'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:644: error: undefined reference to '__cxa_begin_catch'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:646: error: undefined reference to '__cxa_rethrow'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:647: error: undefined reference to '__cxa_end_catch'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:807: error: undefined reference to '__cxa_begin_catch'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:810: error: undefined reference to '__cxa_rethrow'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:811: error: undefined reference to '__cxa_end_catch'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:815: error: undefined reference to '__cxa_begin_catch'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:820: error: undefined reference to '__cxa_rethrow'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qlist.h:821: error: undefined reference to '__cxa_end_catch'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/QtLocationPlugin/QGeoMapReplyQGC.cpp:85: error: undefined reference to 'operator delete(void*)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject.h:266: error: undefined reference to 'operator new(unsigned int)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject.h:266: error: undefined reference to 'operator delete(void*)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject.h:266: error: undefined reference to 'operator new(unsigned int)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject.h:266: error: undefined reference to 'operator new(unsigned int)'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_acquire'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_release'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_abort'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_acquire'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_release'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_abort'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Audio/AudioOutput.cc:76: error: undefined reference to '__cxa_guard_acquire'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Audio/AudioOutput.cc:76: error: undefined reference to '__cxa_guard_release'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Audio/AudioOutput.cc:76: error: undefined reference to '__cxa_guard_abort'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_acquire'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_release'
/Users/himanshu/Qt/5.15.2/android/include/QtCore/qobject_impl.h:75: error: undefined reference to '__cxa_guard_abort'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:52: error: undefined reference to '__cxa_allocate_exception'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:52: error: undefined reference to '__cxa_throw'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:52: error: undefined reference to '__cxa_free_exception'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:54: error: undefined reference to '__cxa_allocate_exception'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:54: error: undefined reference to '__cxa_throw'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:54: error: undefined reference to '__cxa_free_exception'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:86: error: undefined reference to '__cxa_allocate_exception'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:86: error: undefined reference to '__cxa_throw'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:86: error: undefined reference to '__cxa_free_exception'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:295: error: undefined reference to '__cxa_allocate_exception'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:295: error: undefined reference to '__cxa_throw'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/MGRS.cpp:295: error: undefined reference to '__cxa_free_exception'

/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:410: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:410: error: undefined reference to 'std::__ndk1::locale::~locale()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:410: error: undefined reference to 'std::__ndk1::locale::~locale()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:421: error: undefined reference to 'std::__ndk1::ios_base::__set_badbit_and_consider_rethrow()'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/TerrainTile.cc:92: error: undefined reference to 'operator new[](unsigned int)'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/TerrainTile.cc:94: error: undefined reference to 'operator new[](unsigned int)'
obj/FactSystem.o:FactSystem.cc:typeinfo for QQmlPrivate::QQmlElement<Fact>: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/FactSystem.o:FactSystem.cc:typeinfo for QQmlPrivate::QQmlElement<FactMetaData>: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/FactSystem.o:FactSystem.cc:typeinfo for QQmlPrivate::QQmlElement<FactPanelController>: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/VideoStreaming.o:VideoStreaming.cc:typeinfo for QQmlPrivate::QQmlElement<GLVideoItemStub>: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/moc_PlanCreator.o:moc_PlanCreator.cpp:vtable for PlanCreator: error: undefined reference to '__cxa_pure_virtual'
obj/moc_AutoPilotPlugin.o:moc_AutoPilotPlugin.cpp:vtable for AutoPilotPlugin: error: undefined reference to '__cxa_pure_virtual'
obj/moc_AutoPilotPlugin.o:moc_AutoPilotPlugin.cpp:vtable for AutoPilotPlugin: error: undefined reference to '__cxa_pure_virtual'
obj/QGCMapEngine.o:QGCMapEngine.cpp:function __clang_call_terminate: error: undefined reference to 'std::terminate()'
obj/QGCMapTileSet.o(.ARM.extab.text._ZN9QHashData9hasShrunkEv+0x1c): error: undefined reference to 'typeinfo for std::bad_alloc'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Joystick/JoystickAndroid.cc:39: error: undefined reference to 'operator new[](unsigned int)'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Joystick/JoystickAndroid.cc:40: error: undefined reference to 'operator new[](unsigned int)'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:0: error: undefined reference to 'typeinfo for std::length_error'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:0: error: undefined reference to 'std::length_error::~length_error()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:153: error: undefined reference to 'std::logic_error::logic_error(char const*)'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:0: error: undefined reference to 'vtable for std::length_error'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/JoystickAndroid.o:JoystickAndroid.cc:typeinfo for JoystickAndroid: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Joystick/Joystick.cc:102: error: undefined reference to 'operator delete[](void*)'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Joystick/Joystick.cc:122: error: undefined reference to 'operator delete[](void*)'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Joystick/Joystick.cc:123: error: undefined reference to 'operator delete[](void*)'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Joystick/Joystick.cc:124: error: undefined reference to 'operator delete[](void*)'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:0: error: undefined reference to 'typeinfo for std::out_of_range'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:0: error: undefined reference to 'std::out_of_range::~out_of_range()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:164: error: undefined reference to 'std::logic_error::logic_error(char const*)'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/stdexcept:0: error: undefined reference to 'vtable for std::out_of_range'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/Constants.hpp:409: error: undefined reference to 'std::runtime_error::runtime_error(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/Geo/Constants.hpp:400: error: undefined reference to 'std::runtime_error::~runtime_error()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:466: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:466: error: undefined reference to 'std::__ndk1::locale::~locale()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:466: error: undefined reference to 'std::__ndk1::locale::~locale()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:477: error: undefined reference to 'std::__ndk1::ios_base::__set_badbit_and_consider_rethrow()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:651: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:659: error: undefined reference to 'std::__ndk1::ios_base::__set_badbit_and_consider_rethrow()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/__locale:250: error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/__locale:0: error: undefined reference to 'std::__ndk1::num_put<char, std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> > >::id'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:279: error: undefined reference to 'std::uncaught_exception()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ostream:960: error: undefined reference to 'std::__ndk1::ios_base::__set_badbit_and_consider_rethrow()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ios:777: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/__locale:250: error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/__locale:0: error: undefined reference to 'std::__ndk1::ctype<char>::id'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ios:547: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ios:0: error: undefined reference to 'vtable for std::__ndk1::ios_base'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ios:704: error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/ios:711: error: undefined reference to 'std::__ndk1::ios_base::init(void*)'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/streambuf:232: error: undefined reference to 'std::__ndk1::locale::locale()'
obj/UTMUPS.o:UTMUPS.cpp:typeinfo for GeographicLib::GeographicErr: error: undefined reference to 'typeinfo for std::runtime_error'
obj/UTMUPS.o:UTMUPS.cpp:vtable for GeographicLib::GeographicErr: error: undefined reference to 'std::runtime_error::what() const'
obj/UTMUPS.o:UTMUPS.cpp:typeinfo for std::__ndk1::basic_ios<char, std::__ndk1::char_traits<char> >: error: undefined reference to 'typeinfo for std::__ndk1::ios_base'
obj/UTMUPS.o:UTMUPS.cpp:typeinfo for std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/UTMUPS.o:UTMUPS.cpp:typeinfo for std::__ndk1::basic_streambuf<char, std::__ndk1::char_traits<char> >: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/QGCApplication.o:QGCApplication.cc:typeinfo for std::__ndk1::__function::__base<QObject* (QQmlEngine*, QJSEngine*)>: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/QGCApplication.o:QGCApplication.cc:vtable for std::__ndk1::__function::__base<QObject* (QQmlEngine*, QJSEngine*)>: error: undefined reference to '__cxa_pure_virtual'
obj/QGCApplication.o:QGCApplication.cc:typeinfo for QObject* (QQmlEngine*, QJSEngine*): error: undefined reference to 'vtable for __cxxabiv1::__function_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/QGCApplication.o:QGCApplication.cc:typeinfo for QObject* (*)(QQmlEngine*, QJSEngine*): error: undefined reference to 'vtable for __cxxabiv1::__pointer_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1/exception:0: error: undefined reference to 'vtable for std::exception'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/AppMessages.o:AppMessages.cc:typeinfo for QtConcurrent::RunFunctionTaskBase<void>: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/QGCImageProvider.o:QGCImageProvider.cc:typeinfo for QGCImageProvider: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/Users/himanshu/Anra/qgroundcontrol-herelink/src/comm/LinkManager.cc:817: error: undefined reference to '__dynamic_cast'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/comm/LinkManager.cc:830: error: undefined reference to '__dynamic_cast'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/comm/LinkManager.cc:833: error: undefined reference to '__dynamic_cast'
/Users/himanshu/Anra/qgroundcontrol-herelink/src/comm/LinkManager.cc:842: error: undefined reference to '__dynamic_cast'
obj/LinkManager.o:LinkManager.cc:typeinfo for QListSpecialMethods<QList<QVariant> >: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
obj/moc_QGeoCodeReplyQGC.o:moc_QGeoCodeReplyQGC.cpp:vtable for QGeoCodeReplyQGC: error: undefined reference to 'QGeoCodeReplyQGC::~QGeoCodeReplyQGC()'
obj/moc_QGeoCodeReplyQGC.o:moc_QGeoCodeReplyQGC.cpp:vtable for QGeoCodeReplyQGC: error: undefined reference to 'QGeoCodeReplyQGC::~QGeoCodeReplyQGC()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:1660: debug/libQGroundControl_armeabi-v7a.so] Error 1
14:02:58: The process "/Users/himanshu/Library/Android/sdk/ndk/21.3.6528147/prebuilt/darwin-x86_64/bin/make" exited with code 2.
Error while building/deploying project qgroundcontrol (kit: Android Qt 5.15.2 Clang Multi-Abi)
When executing step "Make"
14:02:58: Elapsed time: 13:24.


Best Regards,
Himanshu
